"""Add name and price to Item

Revision ID: 2892772b6619
Revises: eb005453fd83
Create Date: 2025-11-20 19:50:49.345292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2892772b6619'
down_revision = 'eb005453fd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
